"""IR -> Checkstyle config XML."""
import xml.etree.ElementTree as ET
from xml.dom import minidom

_NAMING_MODULES = {"TypeName", "MethodName", "MemberName", "ConstantName",
                   "LocalVariableName", "ParameterName"}

def _module(parent, name):
    return ET.SubElement(parent, "module", {"name": name})

def _prop(mod, name, value):
    ET.SubElement(mod, "property", {"name": name, "value": str(value)})

def _emit_rule(tw, rule):
    ir = rule["ir_rule"]
    p = rule.get("params", {})
    sev = rule["severity"]
    src = rule.get("source_ref", "")
    tw.append(ET.Comment(f" from: {src} ({rule['id']}) "))
    if ir == "max_if_nesting":
        m = _module(tw, "NestedIfDepth"); _prop(m, "max", p.get("max", 1)); _prop(m, "severity", sev)
    elif ir == "max_for_nesting":
        m = _module(tw, "NestedForDepth"); _prop(m, "max", p.get("max", 0)); _prop(m, "severity", sev)
    elif ir == "max_method_lines":
        m = _module(tw, "MethodLength"); _prop(m, "max", p.get("max", 30)); _prop(m, "countEmpty", "false"); _prop(m, "severity", sev)
    elif ir == "max_cyclomatic":
        m = _module(tw, "CyclomaticComplexity"); _prop(m, "max", p.get("max", 3)); _prop(m, "severity", sev)
    elif ir == "forbid_else":
        m = _module(tw, "Regexp"); _prop(m, "format", r"\}\s*else"); _prop(m, "illegalPattern", "true"); _prop(m, "severity", sev)
    elif ir == "naming_regex":
        target = p.get("target", "TypeName")
        if target not in _NAMING_MODULES:
            raise ValueError(f"Unsupported naming target: {target}")
        m = _module(tw, target); _prop(m, "format", p["pattern"]); _prop(m, "severity", sev)
    elif ir == "require_javadoc_tag":
        for tag in p.get("tags", []):
            m = _module(tw, "Regexp"); _prop(m, "format", tag); _prop(m, "illegalPattern", "false"); _prop(m, "severity", sev)
    elif ir == "no_unused_imports":
        m = _module(tw, "UnusedImports"); _prop(m, "severity", sev)
    elif ir == "no_wildcard_imports":
        m = _module(tw, "AvoidStarImport"); _prop(m, "severity", sev)
    elif ir == "no_redundant_imports":
        m = _module(tw, "RedundantImport"); _prop(m, "severity", sev)
    else:
        raise ValueError(f"Unsupported ir_rule for checkstyle backend: {ir}")

def ir_to_checkstyle(ir):
    root = ET.Element("module", {"name": "Checker"})
    root.insert(0, ET.Comment(f" GENERATED by rule-projector — DO NOT EDIT. source_hash={ir.get('source_hash','')} "))
    tw = _module(root, "TreeWalker")
    for rule in ir.get("rules", []):
        _emit_rule(tw, rule)
    raw = ET.tostring(root, encoding="unicode")
    pretty = minidom.parseString(raw).toprettyxml(indent="  ")
    body = pretty.split("?>", 1)[1].lstrip()
    return ('<?xml version="1.0"?>\n'
            '<!DOCTYPE module PUBLIC '
            '"-//Checkstyle//DTD Checkstyle Configuration 1.3//EN" '
            '"https://checkstyle.org/dtds/configuration_1_3.dtd">\n' + body)

def main(argv=None):
    import argparse, json
    from pathlib import Path
    ap = argparse.ArgumentParser()
    ap.add_argument("--ir", required=True)
    ap.add_argument("--out", default="generated/checkstyle.generated.xml")
    args = ap.parse_args(argv)
    ir = json.loads(Path(args.ir).read_text())
    Path(args.out).parent.mkdir(parents=True, exist_ok=True)
    Path(args.out).write_text(ir_to_checkstyle(ir))
    print(f"checkstyle written: {args.out}")
    return 0

if __name__ == "__main__":
    import sys
    sys.exit(main())
